### ISSUE TITLE
Not working in ember 2.7.0

### ISSUE THREAD

**Issue by erichaus** [curtisgr/ember-cli-moment-business#1]
Hello,

I just came across this and tried installing it in an ember 2.7.0 project however it doesn't seem to be importing correctly... Any ideas?

```
`import { addWeekDays } from 'ember-cli-moment-business'`

ShopPanelComponent = Ember.Component.extend
```

**Comment by curtisgr** [comment]
Hi @erichonkanen, sorry for the delay.  Were you able to get this working?

**Comment by curtisgr** [comment]
The destructuring seems to be the issue

```
import { addWeekDays } from 'ember-cli-moment-business';
```

I've tested this and it's working in 2.7.2

```
import business from 'ember-cli-moment-business';

// ...

someFunction () {
  business.addWeekDays(moment(), 20);
}
```

**Comment by curtisgr** [comment]
I'll look into the destructuring issue.
